In [1]:
import numpy as np
import pandas as pd
import time

In [2]:

df= pd.read_csv('./data/EN/train', sep='/n', delimiter=None, names=['original'],index_col=False)
df.head(5)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

           original
0    Municipal B-NP
1        bonds I-NP
2          are B-VP
3  generally B-ADVP
4          a B-ADJP

In [3]:
trainData ='./data/EN/train'
testData ='./data/EN/dev.in'
k =3

In [4]:



def emissionPara(xy,y):
    e_x_y= xy/y
    
    return e_x_y

def preprocess_training(data,k):
    start = time.process_time()   
    
    df= pd.read_csv(data, sep='/n', delimiter=None, names=['original'],index_col=False)
    # dropping null value columns to avoid errors 
    x_dic = {}


    # new data frame with split value columns 
    new = df["original"].str.split(" ", n=1,expand=True) 

    # making separate first name column from new data frame 
    df["x"]= new[0] 

    # making separate last name column from new data frame 
    df["y"]= new[1] 

    # df display 
    uniqueX, uniqueCountX= np.unique(df['x'],return_counts=True)
    for i in range(len(uniqueX)):
        x_dic[uniqueX[i]] = uniqueCountX[i]
        
    replaceWord ="#UNK#"
    for i, text in enumerate(df['x']):
        if x_dic[text] < k:
            df['x'][i] = replaceWord
            df['original'][i]=df['original'][i].replace(text,replaceWord)
    y_dic={}
    uniqueY, uniqueCountY= np.unique(df['y'],return_counts=True)
    for i in range(len(uniqueY)):
        y_dic[uniqueY[i]] = uniqueCountY[i]
        
    xy_dic = {}
    df1= df.copy()
    # Get a tuple of unique values & their count from a numpy array
    df1.dropna(inplace = True) 
    uniqueXY, uniqueCountXY= np.unique(df1['original'].astype(str),return_counts=True)

    for i in range(len(uniqueXY)):
        xy_dic[uniqueXY[i]] = uniqueCountXY[i]
    # print('Unique Values : ', uniqueValues)
    # print('Count of Unique Values : ', uniqueCount)
    dft = pd.DataFrame([uniqueXY,uniqueCountXY]).T
    dft=dft.rename({0:'x_y',1:'count_x_y'},axis='columns')
    
    dft['count_y']=0
    for i,text in enumerate(dft['x_y']):
        data = text.split(" ")
        dft['count_y'][i]=y_dic[data[1]]
        
    dft['emission']=emissionPara(dft['count_x_y'], dft['count_y'])
    
    dft1 = dft.copy()

    # new data frame with split value columns 
    new = dft1["x_y"].str.split(" ", n=1,expand=True) 

    # making separate first name column from new data frame 
    dft1["x"]= new[0] 

    # making separate last name column from new data frame 
    dft1["y"]= new[1] 
    
    xy_pred_dic = {}

    for word in dft1['x']:
        index = pd.Series.idxmax((dft1.loc[dft1['x'] == word]['emission']).astype(float))
        xy_pred_dic[word]=dft1['y'][index] 
    print(time.process_time() - start)
    return xy_pred_dic

In [5]:


def preprocess_test(data,k):
    start = time.process_time()   

    testdf1= pd.read_csv(data, sep='/n', delimiter=None, names=['original'],index_col=False)
    testdf= pd.read_csv(data, sep='/n', delimiter=None, names=['original'],index_col=False,skip_blank_lines=False)

    x_dic = {}

    uniqueX, uniqueCountX= np.unique(testdf1['original'],return_counts=True)
    for i in range(len(uniqueX)):okie 
        x_dic[uniqueX[i]] = uniqueCountX[i]

    replaceWord ="#UNK#"

    testdf['modified']=''
#     print(testdf)
    for i, text in enumerate(testdf['original']):
    #         df['x'][i] = replaceWord
        try:
            if text not in xy_pred_dic:
            
                testdf['modified'][i]=testdf['original'][i].replace(text,replaceWord)
            else:
                testdf['modified'][i]=testdf['original'][i]
        except:
            continue
    testdf['predict_label']=''
    for index, word in enumerate(testdf['modified']):
#     print(word)
        try:
            testdf['predict_label'][index]= xy_pred_dic[word]
        except:
            continue
    print(time.process_time() - start)
    return testdf

In [6]:
xy_pred_dic=preprocess_training(trainData,k)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if sys.path[0] == '':
C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

313.8125

In [7]:
testdf = preprocess_test(testData,k)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  import sys

9.515625

In [8]:
testData ='C:/Users/Asus/Desktop/SUTD/T6/Machine_Learning/Project/data/EN/dev.out'
testresultdf= pd.read_csv(testData, sep='/n', delimiter=None, names=['original'],index_col=False)
testresultdf
new = testresultdf["original"].str.split(" ", n=1,expand=True) 

# making separate first name column from new data frame 
testresultdf["x"]= new[0] 

# making separate last name column from new data frame 
testresultdf["y"]= new[1] 
testresultdf

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

               original            x       y
0              HBO B-NP          HBO    B-NP
1              has B-VP          has    B-VP
2            close B-NP        close    B-NP
3               to I-NP           to    I-NP
4               24 I-NP           24    I-NP
5          million I-NP      million    I-NP
6      subscribers I-NP  subscribers    I-NP
7               to B-PP           to    B-PP
8              its B-NP          its    B-NP
9              HBO I-NP          HBO    I-NP
10             and I-NP          and    I-NP
11         Cinemax I-NP      Cinemax    I-NP
12        networks I-NP     networks    I-NP
13                  , O            ,       O
14         while B-SBAR        while  B-SBAR
15        Showtime B-NP     Showtime    B-NP
16                and O          and       O
17             its B-NP          its    B-NP
18          sister I-NP       sister    I-NP
19         service I-NP      service    I-NP
20                  , O            ,       O
21             The B-NP          The    B-NP
22           Movie I-NP        Movie    I-NP
23         Channel I-NP      Channel    I-NP
24                  , O            ,       O
25            have B-VP         have    B-VP
26            only B-NP         only    B-NP
27           about I-NP        about    I-NP
28              10 I-NP           10    I-NP
29         million I-NP      million    I-NP
...                 ...          ...     ...
26101           's B-NP           's    B-NP
26102     slowdown I-NP     slowdown    I-NP
26103           is B-VP           is    B-VP
26104        due B-ADJP          due  B-ADJP
26105       only I-ADJP         only  I-ADJP
26106     partly I-ADJP       partly  I-ADJP
26107           to B-PP           to    B-PP
26108          the B-NP          the    B-NP
26109    austerity I-NP    austerity    I-NP
26110      program I-NP      program    I-NP
26111     launched B-VP     launched    B-VP
26112           in B-PP           in    B-PP
26113    September B-NP    September    B-NP
26114         1988 I-NP         1988    I-NP
26115           to B-VP           to    B-VP
26116         cool I-VP         cool    I-VP
26117           an B-NP           an    B-NP
26118   overheated I-NP   overheated    I-NP
26119      economy I-NP      economy    I-NP
26120             and O          and       O
26121         tame B-VP         tame    B-VP
26122    inflation B-NP    inflation    B-NP
26123               . O            .       O
26124          The B-NP          The    B-NP
26125          GOP I-NP          GOP    I-NP
26126     doubters I-NP     doubters    I-NP
26127         were B-VP         were    B-VP
26128           in B-PP           in    B-PP
26129     Congress B-NP     Congress    B-NP
26130               . O            .       O

[26131 rows x 3 columns]

In [9]:
final = pd.DataFrame()
final['result'] = testdf['modified'] + ' ' + testdf['predict_label']
final.head(5)

         result
0      HBO B-NP
1      has B-VP
2  close B-ADJP
3       to B-PP
4       24 I-NP

In [11]:
f = open('./data/EvalScript/dev.prediction','w')
for word in final['result']:
    f.write(word + '\n')
f.close()